### ISSUE TITLE
Ability to toggle off blue overlay

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/node-map#14]
Blue overlay from sector beams obscures map. There needs to be some way to toggle it completely off. East Village is particularly bad, and now Greenpoint is too

**Comment by bhny** [comment]
![Screen Shot 2019-08-02 at 5 51 02 PM](https://user-images.githubusercontent.com/1037006/62400710-31daa500-b54e-11e9-9cad-9b53f6f357b3.png)

**Comment by bhny** [comment]
Please?

**Comment by bhny** [comment]
Maybe we could add toggle (default off) at the bottom of the map-
![Screen Shot 2019-08-02 at 6 05 12 PM](https://user-images.githubusercontent.com/1037006/62402280-f98a9500-b554-11e9-9d72-e711a3fdbbd1.png)

**Comment by olivernyc** [comment]
Reduced opacity and added a toggle in https://github.com/nycmeshnet/node-map/pull/12
