### ISSUE TITLE
dead nodes show on map

### ISSUE THREAD

**Issue by bhny** [nycmeshnet/node-map#3]
There's 3 states of nodes that should be hidden- "Not interested", "Unsubscribe" and "Abandoned"

<img width="120" alt="node-states" src="https://user-images.githubusercontent.com/1037006/46633668-60e5dd00-cb1c-11e8-9dc2-49e79960b76c.png">

**Comment by olivernyc** [comment]
Fixed in https://github.com/nycmeshnet/node-db/commit/0489d4db502928b5423da8714d8a4debb418b949
